--[[---------------------------------------------------------------------------
DarkRP custom jobs
---------------------------------------------------------------------------

This file contains your custom jobs.
This file should also contain jobs from DarkRP that you edited.

Note: If you want to edit a default DarkRP job, first disable it in darkrp_config/disabled_defaults.lua
	Once you've done that, copy and paste the job to this file and edit it.

The default jobs can be found here:
https://github.com/FPtje/DarkRP/blob/master/gamemode/config/jobrelated.lua

For examples and explanation please visit this wiki page:
http://wiki.darkrp.com/index.php/DarkRP:CustomJobFields


Add jobs under the following line:
---------------------------------------------------------------------------]]
TEAM_CADET = DarkRP.createJob("Clone Cadet", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/asgclonewars/clone_cadet/clone_cadet.mdl"},
   description = [[A CLONE TROOPER IN TRAINING]],
   weapons = {},
   command = "BECOMECADET",
   max = 40,
   salary = 0,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
    PlayerLoadout = function(ply) ply:SetHealth(250) end,
   F4JobFilter = "Clones",
   customCheck = function(ply) return PlychangeAllowed(ply,"Clone Cadet") end,
   CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_CLONETROOPER = DarkRP.createJob("Clone Trooper", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/testw/cgi ct.mdl"},
   description = [[A CLONE TROOPER FOR THE REPUBLIC]],
   weapons = {"weapon_752_dc15sa","weapon_752_dc15a",},
   command = "BECOMECT",
   max = 20,
   salary = 50,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   PlayerLoadout = function(ply) ply:SetHealth(250) end,
   F4JobFilter = "Clones",
   customCheck = function(ply) return PlychangeAllowed(ply,"Clone Trooper") end,
   CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_CLONETROOPERCOMMANDER = DarkRP.createJob("Clone Trooper Commander", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/ponds/ponds.mdl"},
   description = [[A CLONE TROOPER COMMANDER FOR THE REPUBLIC]],
   weapons = {"weapon_752_dc15a","weapon_752_dc15sa","weapon_752_dc17dual"},
   command = "BECOMECTCMDR",
   max = 1,
   salary = 50,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = false,
   PlayerLoadout = function(ply) ply:SetHealth(250) end,
   F4JobFilter = "Clones",
   customCheck = function(ply) return PlychangeAllowed(ply,"Clone Trooper Commander") end,
   CustomCheckFailMsg = "You are not in the withelist!",
})
----------------------------------------Shadow Squad-------------------------------------------------------
TEAM_ShadowCOM = DarkRP.createJob("Shadow Battalion Commander", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/arcg/arcg.mdl"},
   description = [[You are the Commander of Shadow Battalion]],
   weapons = {"weapon_752_t21","weapon_752_dc15a","weapon_752_dc17dual",},
   command = "shadowcom",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Shadow Squad",
})
TEAM_SHADOWCO = DarkRP.createJob("Shadow CO", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/badblt/badblt.mdl"},
   description = [[You are a CO in Shadow Battalion]],
   weapons = {"weapon_752_t21","weapon_752_dc15a","weapon_752_dc17",},
   command = "shadowco",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "",
})
TEAM_SHADOWTRP = DarkRP.createJob("Shadow Battalion Trooper", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/badbt/cbadbt.mdl"},
   description = [[You are a Shadow Battalion Trooper]],
   weapons = {"weapon_752_t21","weapon_752_dc15a","weapon_752_dc17",},
   command = "shdtrp",
   max = 20,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Shadow Squad",
})
------------------------------------212th------------------------------------------
TEAM_212CO = DarkRP.createJob("212th Commander Cody", {
   color = Color(255, 229, 0, 255),
   model = {"models/player/testccc/ccody.mdl"},
   description = [[You Are The 212th Commander]],
   weapons = {"weapon_752_dc15a","weapon_752_dc15s"},
   command = "212thCO",
   max = 1,
   salary = 20,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   PlayerLoadout = function(ply) ply:SetHealth(250) end,
   F4JobFilter = "212th",
   customCheck = function(ply) return PlychangeAllowed(ply,"212th Commander") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_212 = DarkRP.createJob("212th Trooper", {
   color = Color(255, 229, 0, 255),
   model = {"models/player/212th/c212th trooper.mdl"},
   description = [[You Are The 212th Trooper]],
   weapons = {"weapon_752_dc15a","weapon_752_dc15s"},
   command = "212th",
   max = 15,
   salary = 20,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   PlayerLoadout = function(ply) ply:SetHealth(200) end,
   F4JobFilter = "212th",
   customCheck = function(ply) return PlychangeAllowed(ply,"212th Trooper") end,
CustomCheckFailMsg = "You are not in the withelist!",
})

TEAM_212LT = DarkRP.createJob("212th Officer", {
   color = Color(255, 229, 0, 255),
   model = {"models/player/212thlt/c212thlt.mdl"},
   description = [[You Are The 212th Officer]],
   weapons = {"weapon_752_dc15a","weapon_752_dc15s"},
   command = "212thLT",
   max = 5,
   salary = 20,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   PlayerLoadout = function(ply) ply:SetHealth(250) end,
   F4JobFilter = "212th",
   customCheck = function(ply) return PlychangeAllowed(ply,"212th Officer") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
----------------------------------------Jedi------------------------------------------------

TEAM_KENOBI = DarkRP.createJob ("Jedi General Obi Wan Kenobi", {
     color = Color(146, 40, 143, 255),
     model = {"models/player/generalkenobi/cgikenobi.mdl"},
     description = [[Obi Wan Kenobi.]],
     weapons = {"weapon_lightsaber"},
     command = "kenobi",
     max = 1,
     salary = 20,
     admin = 0,
     vote = false,
     hasLicense = false,
     candemote = false,
     PlayerLoadout = function(ply) ply:SetHealth(5000) end,
     F4JobFilter = "Jedi",    
	 customCheck = function(ply) return PlychangeAllowed(ply,"Jedi General Obi Wan Kenobi") end,
CustomCheckFailMsg = "You are not in the withelist!",
})

TEAM_KOON = DarkRP.createJob ("Jedi General Plo Koon", {
     color = Color(146, 40, 143, 255),
     model = {"models/player/plokoon/plokoon.mdl"},
     description = [[General Plo Koon.]],
     weapons = {"weapon_lightsaber"},
     command = "koon",
     max = 1,
     salary = 20,
     admin = 0,
     vote = false,
     hasLicense = false,
     candemote = false,
     PlayerLoadout = function(ply) ply:SetHealth(5000) end,
     F4JobFilter = "Jedi",    
	 customCheck = function(ply) return PlychangeAllowed(ply,"Jedi General Plo Koon") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_ANAKIN = DarkRP.createJob ("Jedi General Anakin Skywalker", {
     color = Color(146, 40, 143, 255),
     model = {"models/kriegsyntax/sw_752/anakin_est.mdl"},
     description = [[General Anakin Skywalker.]],
     weapons = {"weapon_lightsaber"},
     command = "anakin",
     max = 1,
     salary = 20,
     admin = 0,
     vote = false,
     hasLicense = false,
     candemote = false,
     PlayerLoadout = function(ply) ply:SetHealth(5000) end,
     F4JobFilter = "Jedi",    
	 customCheck = function(ply) return PlychangeAllowed(ply,"Jedi General Anakin Skywalker") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_WINDU = DarkRP.createJob ("Jedi General Mace Windu", {
     color = Color(146, 40, 143, 255),
     model = {"models/player/mace/mace.mdl"},
     description = [[General Mace Windu.]],
     weapons = {"weapon_lightsaber"},
     command = "windu",
     max = 1,
     salary = 20,
     admin = 0,
     vote = false,
     hasLicense = false,
     candemote = false,
     PlayerLoadout = function(ply) ply:SetHealth(5000) end,
     F4JobFilter = "Jedi",    
	 customCheck = function(ply) return PlychangeAllowed(ply,"Jedi General Mace Windu") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_YODA = DarkRP.createJob ("Jedi General Yoda", {
     color = Color(146, 40, 143, 255),
     model = {"models/player/b4p/b4p_yoda.mdl"},
     description = [[General Yoda.]],
     weapons = {"weapon_lightsaber"},
     command = "yoda",
     modelScale = 0.6,
     max = 1,
     salary = 20,
     admin = 0,
     vote = false,
     hasLicense = false,
     candemote = false,
     PlayerLoadout = function(ply) ply:SetHealth(5000) end,
     F4JobFilter = "Jedi",    
	 customCheck = function(ply) return PlychangeAllowed(ply,"Jedi General Yoda") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_GRANDMASTER = DarkRP.createJob("Grand Master", {
   color = Color(255, 0, 0, 255),
   model = {"models/jazzmcfly/jka/jtg/jtg.mdl"},
   description = [[You are the Jedi Master!]],
   weapons = {"weapon_lightsaber"},
   command = "grandmaster",
   max = 5,
   salary = 50,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   PlayerLoadout = function(ply) ply:SetHealth(5000) end,
   F4JobFilter = "Jedi",
   customCheck = function(ply) return PlychangeAllowed(ply,"Grand Master") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_JEDIMASTER = DarkRP.createJob("Jedi Master", {
   color = Color(255, 0, 0, 255),
   model = {"models/grealms/characters/jedibattlelord/jedibattlelord_07.mdl"},
   description = [[You are the Jedi Master!]],
   weapons = {"weapon_lightsaber"},
   command = "jedimaster",
   max = 5,
   salary = 50,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   PlayerLoadout = function(ply) ply:SetHealth(5000) end,
   F4JobFilter = "Jedi",
   customCheck = function(ply) return PlychangeAllowed(ply,"Jedi Master") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_JEDIKNIGHT = DarkRP.createJob("Jedi Knight", {
   color = Color(255, 0, 0, 255),
   model = {"models/grealms/characters/jedirobes/jedirobes_05.mdl"},
   description = [[Your a Jedi Knight!]],
   weapons = {"weapon_lightsaber"},
   command = "jediknight",
   max = 5,
   salary = 50,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   PlayerLoadout = function(ply) ply:SetHealth(5000) end,
   F4JobFilter = "Jedi",
   customCheck = function(ply) return PlychangeAllowed(ply,"Jedi Knight") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
TEAM_JEDIPADAWAN = DarkRP.createJob("Jedi Padawan", {
   color = Color(255, 0, 0, 255),
   model = {"models/player/light_revan.mdl"},
   description = [[Your a Jedi Knight!]],
   weapons = {"weapon_lightsaber"},
   command = "jedipadawan",
   max = 5,
   salary = 50,
   admin = 0,
   vote = false,
   hasLicense = false,
   candemote = false,
   PlayerLoadout = function(ply) ply:SetHealth(5000) end,
   F4JobFilter = "Jedi",
   customCheck = function(ply) return PlychangeAllowed(ply,"Jedi Padawan") end,
CustomCheckFailMsg = "You are not in the withelist!",
})
-----------------------------------------------GM----------------------------------------------
TEAM_GALACTICCOM = DarkRP.createJob("Galactic Marine Commander", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/tcg/starwars/gm/bacara/bacara.mdl"},
   description = [[You are the Galactic Marine Commander]],
   weapons = {"weapon_752_dc15a","weapon_752_dc17dual",},
   command = "gmcom",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Galactic Marines",
})
TEAM_GALACTICCO = DarkRP.createJob("Galactic Marine CO", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/tcg/starwars/gm/captain/gmcaptain.mdl"},
   description = [[You are a Galactic Marine CO]],
   weapons = {"weapon_752_dc15a","weapon_752_dc17",},
   command = "gmco",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Galactic Marines",
})
TEAM_GALACTICTRP = DarkRP.createJob("Galactic Marine Trooper", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/tcg/starwars/gm/galacticmarine.mdl"},
   description = [[You are a Galactic Marine trooper]],
   weapons = {"weapon_752_dc15a","weapon_752_dc17",},
   command = "gmtrp",
   max = 20,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Galactic Marines",
})
------------------------------------ARC------------------------------------------------------------------------
-- Code generated at: TheCodingBeast.com | DarkRP 2.5 Tools
TEAM_ARCOM = DarkRP.createJob("ARC Commander", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/yarc/cgicyarc.mdl"},
   description = [[The Commander of the Elite ARC Battalion]],
   weapons = {"weapon_752_dc17m_br", "weapon_752_dc17","dc17grapple",},
   command = "ARCCOM",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "ARC",
})
TEAM_ARCCO = DarkRP.createJob("ARC CO", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/garc/garc.mdl"},
   description = [[You are a CO in ARC Battalion]],
   weapons = {"weapon_752_dc17m_br", "weapon_752_dc17","dc17grapple",},
   command = "ARCCO",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "ARC",
})
TEAM_ARC = DarkRP.createJob("ARC Trooper", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/barc/cgicbarc.mdl"},
   description = [[You are an elite ARC Trooper]],
   weapons = {"weapon_752_dc17m_br", "weapon_752_dc17","dc17grapple",},
   command = "arc",
   max = 20,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "ARC",
})
----------------------------------------------------612TH-------------------------------------------
TEAM_612COM = DarkRP.createJob("612th Commander", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/fox/ccfox.mdl"},
   description = [[Your the commander in the 612th Attack Battalion]],
   weapons = {"weapon_752_dc15a","weapon_752_dc17",},
   command = "612COM",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "612th Attack Battalion",
})
TEAM_612thCO = DarkRP.createJob("612th CO", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/rarc/cgirarc.mdl"},
   description = [[You are a CO for the 612th]],
   weapons = {"weapon_752_dc15a", "weapon_752_dc17",},
   command = "612thCO",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "612th Attack Battalion",
})
Team_612THTROOPER = DarkRP.createJob("612th Trooper", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/cguard/cgi cguard.mdl"},
   description = [[You are a trooper in the 612th]],
   weapons = {"weapon_752_dc15a","weapon_752_dc17",},
   command = "612thTrooper",
   max = 20,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "612th Attack Battalion",
})
-----------------------------------------Pilot---------------------------------------
TEAM_PILOTCOM = DarkRP.createJob("Pilot Commander", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/specopspilot/specopspilot.mdl"},
   description = [[You are the Pilot Squadron Commander]],
   weapons = {"weapon_752_dl44",},
   command = "pilotcom",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Pilot",
})
TEAM_PILOTCOM = DarkRP.createJob("Yellow Squadron Leader", {
   color = Color(249, 255, 0, 255),
   model = {"models/player/rayl/rayl.mdl"},
   description = [[You are the leader of Blue Sqadron]],
   weapons = {"weapon_752_dl44",},
   command = "Yl",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Pilot",
})
TEAM_PILOT = DarkRP.createJob("Yellow Squadron Pilot", {
   color = Color(249, 255, 0, 255),
   model = {"models/player/medt/medt.mdl"},
   description = [[You are a Clone Pilot]],
   weapons = {"weapon_752_dc17",},
   command = "pilot",
   max = 13,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Pilot",
})
TEAM_PILOTCOM = DarkRP.createJob("Blue Squadron Leader", {
   color = Color(5, 0, 255, 255),
   model = {"models/player/rayl/rayl.mdl"},
   description = [[You are the leader of Blue Sqadron]],
   weapons = {"weapon_752_dl44",},
   command = "bl",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Pilot",
})
TEAM_PILOT = DarkRP.createJob("Blue Squadron Pilot", {
   color = Color(5, 0, 255, 255),
   model = {"models/player/bst/bst.mdl"},
   description = [[You are the leader of Blue Sqadron.]],
   weapons = {"weapon_752_dl44",},
   command = "bl",
   max = 3,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
  -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Pilots",
})
TEAM_PILOTCOM = DarkRP.createJob("Black Squadron Pilot", {
   color = Color(0, 0, 0, 255),
   model = {"models/player/krieg/ckrieg.mdl"},
   description = [[You are the leader of Blue Sqadron]],
   weapons = {"weapon_752_dl44",},
   command = "bp",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Pilot",
})
---------------------------------------501st-------------------------------------------
TEAM_501stco = DarkRP.createJob("501st CO", {
   color = Color(5, 0, 255, 255),
   model = {"models/player/trap/trapm.mdl"},
   description = [[You are a 501st C0]],
   weapons = {"weapon_752_dc17dual","weapon_752dc15a",},
   command = "501CO",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "501st",
})

TEAM_REX = DarkRP.createJob("Captain Rex", {
   color = Color(73, 71, 168, 255),
   model = {"models/player/test/rex.mdl"},
   description = [[You are Captain Rex of the 601st]],
   weapons = {"weapon_752_dc15a","weapon_752_dc17dual","weapon_752_dc15s",},
   command = "rex",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "501st",
})
TEAM_501STTRP = DarkRP.createJob("501st Trooper", {
   color = Color(73, 71, 168, 255),
   model = {"models/player/501st/c501st.mdl"},
   description = [[You are a trooper in the 601st]],
   weapons = {"weapon_752_dc15a","weapon_752_dc17","weapon_752_dc15s",},
   command = "501sttrp",
   max = 20,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "501st",
})
------------------------Engineer----------------------------------------
TEAM_ENGCOM = DarkRP.createJob("Engineer Commander", {
   color = Color(255, 168, 0, 255),
   model = {"models/player/sgg/ktarwars/klonetrooper.mdl
"},
   description = [[You are an Engineer Commader]],
   weapons = {"weapon_752_dc17",},
   command = "EnginCom",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Engineer",
})
TEAM_EOD = DarkRP.createJob("EOD Trooper", {
   color = Color(255, 168, 0, 255),
   model = {"models/player/teste/cgi eod.mdl"},
   description = [[You are an EOD Trooper]],
   weapons = {"weapon_752_dc17","weapon_752_dc15s",},
   command = "EOD",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Engineer",
})
TEAM_ENG = DarkRP.createJob("Engineer", {
   color = Color(255, 168, 0, 255),
   model = {"models/player/clone engineer/ccgi engineer.mdl"},
   description = [[You are an Engineer]],
   weapons = {"weapon_752_dc17",},
   command = "Engin",
   max = 10,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Engineer",
})
----------------------------------------Shocktrooper---------------------------------
TEAM_ESCO = DarkRP.createJob("Elite Shocktrooper Commander", {
   color = Color(255, 255, 255, 255),
   model = {"models/gamingbro/characters/reptroopexalted/reptroopexalted.mdl"},
   description = [[You are an Elite Shocktrooper Commander]],
   weapons = {"weapon_lasermgun","dc17grapple","weapon_752_e60r","weapon_752_dlt19",},
   command = "ELITECO",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Shocktrooper",
})



TEAM_ES = DarkRP.createJob("Elite Shocktrooper", {
   color = Color(255, 255, 255, 255),
   model = {"models/player/deckboy/havoc_trooper_pm/havoc_trooper_pm.mdl"},
   description = [[You are an Elite Shocktrooper]],
   weapons = {"weapon_lasermgun","dc17grapple","weapon_752_e60r",},
   command = "elite",
   max = 10,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Shocktrooper",
})
------------------------------------Navy-------------------------------------
TEAM_FLEETOF = DarkRP.createJob("Fleet Officer", {
   color = Color(130, 130, 130, 255),
   model = {"models/player/donut/donut.mdl"},
   description = [[You are a Fleet Officer]],
   weapons = {"weapon_752_dc17"},
   command = "FLEETOF",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fleet",
})
TEAM_FLEETCOM = DarkRP.createJob("Fleet Commander", {
   color = Color(130, 130, 130, 255),
   model = {"models/player/donut/donut.mdl"},
   description = [[You are a Fleet Commander]],
   weapons = {"weapon_752_dc17"},
   command = "FLEETCOM",
   max = 5,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fleet",
})
TEAM_REARADMIRAL = DarkRP.createJob("Rear Admiral", {
   color = Color(130, 130, 130, 255),
   model = {"models/player/hawk/comhawk.mdl"},
   description = [[You are a Rear Admiral]],
   weapons = {"weapon_752_dc17"},
   command = "ADM",
   max = 2,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fleet",
})
TEAM_VCAD = DarkRP.createJob("Vice Admiral", {
   color = Color(255, 255, 255, 255),
   model = {"models/player/hawk/comhawk.mdl"},
   description = [[You are a Vice Admiral]],
   weapons = {"weapon_752_dc17"},
   command = "VCAD",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fleet",
})
TEAM_AD = DarkRP.createJob("Admiral", {
   color = Color(255, 255, 255, 255),
   model = {"models/player/wullf/wullf.mdl"},
   description = [[You are a Admiral]],
   weapons = {"weapon_752_dc17"},
   command = "AD",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fleet",
})
TEAM_GA = DarkRP.createJob("Grand Admiral", {
   color = Color(255, 255, 255, 255),
   model = {"models/player/wullf/wullf.mdl"},
   description = [[You are a Grand Admiral]],
   weapons = {"weapon_752_dc17"},
   command = "GAD",
   max = 1,
   salary = 250,
   admin = 0,
   vote = false,
   hasLicense = true,
   candemote = true,
   -- CustomCheck
   medic = false,
   chief = false,
   mayor = false,
   hobo = false,
   cook = false,
   category = "Fleet",
})

--[[---------------------------------------------------------------------------
Define which team joining players spawn into and what team you change to if demoted
---------------------------------------------------------------------------]]
GAMEMODE.DefaultTeam = TEAM_CADET


--[[---------------------------------------------------------------------------
Define which teams belong to civil protection
Civil protection can set warrants, make people wanted and do some other police related things
---------------------------------------------------------------------------]]
GAMEMODE.CivilProtection = {
	[TEAM_POLICE] = true,
	[TEAM_CHIEF] = true,
	[TEAM_MAYOR] = true,
}

--[[---------------------------------------------------------------------------
Jobs that are hitmen (enables the hitman menu)
---------------------------------------------------------------------------]]
DarkRP.addHitmanTeam(TEAM_MOB)
